configfile: "config/snakebids.yml"


include: "rules/setup.smk"
include: "rules/common.smk"
include: "rules/workflowopts.smk"
include: "rules/prepdwi.smk"
include: "rules/sdc.smk"
include: "rules/eddy.smk"
include: "rules/bedpost.smk"
include: "rules/reg_dwi_to_t1.smk"
include: "rules/masking_bet_from-b0.smk"
include: "rules/masking_b0_to_template.smk"
include: "rules/reg_t1_to_template.smk"
include: "rules/seg_t1_brain_tissue.smk"
include: "rules/masking_b0_synthstrip.smk"


if config["use_eddy_s2v"] and not config["use_eddy_gpu"]:
    print(
        "ERROR: Eddy Slice-to-volume correction (--use-eddy-s2v) must be used with eddy GPU (--use-eddy-gpu)"
    )
    sys.exit(1)


rule all:
    input:
        **get_eddy_quad_all(),
        **get_bedpost_all(),
        mask_qc=expand(
            bids(
                root=root,
                datatype="qc",
                suffix="mask.png",
                desc="brain",
                **subj_wildcards
            ),
            zip,
            **subj_zip_list
        ),
        reg_qc=expand(
            bids(
                root=root,
                datatype="qc",
                suffix="reg.png",
                from_="dwiref",
                to="T1w",
                **subj_wildcards
            ),
            zip,
            **subj_zip_list
        ),
        dtifit=expand(
            bids(
                root=root,
                datatype="dwi",
                suffix="dtifit",
                desc="eddy",
                space="T1w",
                res=config["resample_dwi"]["resample_scheme"],
                **subj_wildcards
            ),
            zip,
            **subj_zip_list
        ),


rule all_metacheck:
    input:
        missing_subj_tsv=bids(root=root, suffix="missing.tsv"),
        metadata_subj_tsv=bids(root=root, suffix="metadata.tsv"),
