configfile: "config/snakebids.yml"

# Workflow setup rules
include: "rules/setup.smk"
include: "rules/common.smk"
include: "rules/workflowopts.smk"
# Anatomical
include: "rules/anatomical/anatomical.smk"
include: "rules/anatomical/reg_t1_to_template.smk"
include: "rules/anatomical/seg_t1_brain_tissue.smk"
# Pre-SDC rules
include: "rules/diffusion/prepdwi.smk"
include: "rules/diffusion/motioncorr.smk"
# B0 Masking rules
include: "rules/diffusion/masking/masking_bet_from-b0.smk"
include: "rules/diffusion/masking/masking_b0_to_template.smk"
include: "rules/diffusion/masking/masking_b0_synthstrip.smk"
# SDC rules
include: "rules/gradcorrect.smk"
include: "rules/sdc.smk"
include: "rules/diffusion/sdc/topup.smk"
include: "rules/diffusion/sdc/sdcflows.smk"
include: "rules/diffusion/sdc/synthsr.smk
# Registration
include: "rules/diffusion/reg_dwi_to_t1.smk"

include: "rules/eddy.smk"
include: "rules/bedpost.smk"
# Currently unused
# include: rules/other.smk
# include: rules/templateflow.smk
# include: rules/visqc.smk



# Incompatible config options
if config["use_eddy_s2v"] and not config["use_eddy_gpu"]:
    print(
        "ERROR: Eddy Slice-to-volume correction (--use-eddy-s2v) must be used "
        "with eddy GPU (--use-eddy-gpu)."
    )
    sys.exit(1)


rule all:
    input:
        **get_eddy_quad_all(),
        **get_bedpost_all(),
        mask_qc=expand(
            bids(
                root=root,
                datatype="qc",
                suffix="mask.png",
                desc="brain",
                **subj_wildcards
            ),
            zip,
            **subj_zip_list
        ),
        reg_qc=expand(
            bids(
                root=root,
                datatype="qc",
                suffix="reg.png",
                from_="dwiref",
                to="T1w",
                **subj_wildcards
            ),
            zip,
            **subj_zip_list
        ),
        dtifit=expand(
            bids(
                root=root,
                datatype="dwi",
                suffix="dtifit",
                desc="eddy",
                space="T1w",
                res=config["resample_dwi"]["resample_scheme"],
                **subj_wildcards
            ),
            zip,
            **subj_zip_list
        ),


rule all_metacheck:
    input:
        missing_subj_tsv=bids(root=root, suffix="missing.tsv"),
        metadata_subj_tsv=bids(root=root, suffix="metadata.tsv"),
