---
name: Lint and test workflow
on:
  pull_request:
jobs:
  quality:
    name: Lint code
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@master
      #----------------------------------------------
      #  -----  install & configure pixi  -----
      #----------------------------------------------
      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          cache: true
      #----------------------------------------------
      #       run python style checks
      #----------------------------------------------
      - name: Run quality checks
        run: pixi run quality_check
  test:
    runs-on: ubuntu-latest
    needs: [quality]
    steps:
      - name: Clone repo
        uses: actions/checkout@master
      #----------------------------------------------
      #  -----  install & configure pixi  -----
      #----------------------------------------------
      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.39.5
          cache: true
      #----------------------------------------------
      # Run all tests
      #----------------------------------------------
      - name: Run all tests
        run: pixi run test_all
